name: AlphaDataCenterCooling
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - matplotlib=3.8.3
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=23.3.1
  - flask=2.3.3
  - flask-cors=4.0.0
  - requests=2.31.0
  - pytorch
  - tqdm
  - pip:
    - chardet==5.2.0
    - gymnasium==0.29.1
    - simplejson==3.19.2
    - flask-restful==0.3.10
    - werkzeug==2.3.7
    - fmpy==0.3.20
