name: AlphaDataCenterCooling
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.13
  - matplotlib=3.8.3
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=23.3.1
  - pip:
    - chardet==5.2.0
    - gymnasium==0.29.1
    - simplejson==3.19.2
    - tqdm==4.66.2
    - requests==2.31.0
